### PR TITLE
fix for #20

### PR DESCRIPTION
**Pull request by zefanja**

### CODE REVIEW

**Comment by HappyBasher** [comment]
Has been fixed in [7.0.0-47](https://github.com/linuxmuster/linuxmuster-base7/tree/7.0.0-47). Still not working?

**Comment by zefanja** [comment]
Yes, the problem is when you provide a custom config in unattended mode (like the webUI does). Currently the script sets skipfw to false and write it to the config file without reading the value in config file provided by the `-c` option.

**Comment by HappyBasher** [comment]
Has been fixed in [7.0.0-47](https://github.com/linuxmuster/linuxmuster-base7/tree/7.0.0-47). Still not working?

**Comment by HappyBasher** [comment]
Issue is not reproduceable for me. If I invoke _linuxmuster-setup_ in unattended mode with the following _setup.ini_ firewall setup is skipped as expected:  
```
[setup]  
servername = server  
domainname = linuxmuster.lan  
opsiip =
dockerip =
mailip =
dhcprange = 10.0.255.1 10.0.255.250
smtprelay =
smtpuser =
smtppw =
adminpw = Muster!
schoolname = Linuxmuster
location = Schönau
country = DE
state = BW
skipfw = True
```

**Comment by zefanja** [comment]
If I run `linuxmuster-setup -u -c config.ini` (like the webUI) with your config file, `/var/cache/linuxmuster/custom.ini` looks like this:

```
[setup]
...
skipfw = False
```
Skipping the firewall only works if I use the `-s` option. Otherwise `skipfw` is always `False`.

**Comment by HappyBasher** [comment]
Fixed in 7.0.26. There was a logical error in linuxmuster-setup which caused the skipfw option been overwritten.

**Pull request closed without merging**
